services:
  erp-gateway:
    image: nginx:1.27-alpine
    container_name: erp-gateway
    ports:
      - "7080:7080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ../wms-web/dist:/srv/apps/wms:ro
      - ../pms-web/dist:/srv/apps/pms:ro
      - ../oms-web/dist:/srv/apps/oms:ro
      - ../procurement-web/dist:/srv/apps/procurement:ro
      - ../logistics-web/dist:/srv/apps/logistics:ro
    restart: unless-stopped
